version: '3'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379
